---
title: "bt_universe"
author: "Eloïse Vannier
format: html
---

```{r}
#| message: false
here::i_am("bt_universe.Rproj")
library(here)
library(vroom)
library(dplyr)
library(tidyr)
library(ggplot2)
```

Here is the link to the corresponding github repository : [github_repository](https://github.com/E10is3/bt_universe.git)

## Loading the main data set
```{r}
#| message: false
Star_plus_systems <- vroom(here("data", "Star+systems.csv"), delim=";", col_names = TRUE,col_types=NULL, show_col_types=T,locale=locale(decimal_mark = ","))
if (NROW(Star_plus_systems)!=1074){
  print("There is a problem with the loading")
}else if(NCOL(Star_plus_systems)!=8){
   print("There is a problem with the loading")
}
```

## Description of the main data set
```{r}
#| message: false
Star_plus_systems |> summarise("nb of observations" = NROW(Star_plus_systems),"nb of variables"= NCOL(Star_plus_systems))|>
  knitr::kable(align = 'c', caption = "Star_plus_systems data set properties")
```

# 2 Introductory analysis

```{r}
ggplot(Star_plus_systems, aes(x = Mass, y=luminosity))+geom_point(na.rm = TRUE,alpha=0.1)
```
We can see that the luminosity of a star is linked to its mass : stars that weight less tend to diffuse less light.

